service: serverless-typescript-typeorm
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2

functions:
  - ${file(./src/functions/enterprises/index.functions.yml)}

plugins:
  - serverless-offline
  - serverless-plugin-typescript